title: 设计相关
icon: fa-paint-brush
subMenu:
  - title: icon图标
    links:
      - title: icones
        description: 各种类型的icon图标，供代码中引用
        url: "https://icones.js.org/"
        logo: icones.png
      - title: flaticon
        description: 免费下载icon和贴纸
        url: "https://www.flaticon.com/"
        logo: flaticon.png
      - title: icons
        description: 收集了很多图标、插图、音乐、设计工具等
        url: https://igoutu.cn/
        logo: ""
      - title: worldvectorlogo
        description: 收录了世界各地的矢量 LOGO图标
        url: https://worldvectorlogo.com/
        logo: ""
      - title: iconbolt
        description: 7w多个SVG 图标的仓库,免费使用
        url: https://www.iconbolt.com/
        logo: ""
      - title: tabler-icons
        description: 一组超过 3400 个免费的 MIT 许可的高质量 SVG 图标
        url: https://tabler-icons.io/
        logo: ""
  - title: 设计资源
    links:
      - title: 中国色
        description: 罗列了中国的传统色彩，界面过渡流畅治愈
        url: http://zhongguose.com/
        logo: ""
      - title: 中国色彩
        description: 罗列了中国的传统色彩，UI设计更加漂亮
        url: https://chinese-colors.heyfe.org/
        logo: ""
      - title: storyset
        description: 提供免费的插画图
        url: https://storyset.com/
        logo: ""
      - title: htmlrev
        description: 免费提供多个 landing page 样式供下载
        url: https://htmlrev.com/
        logo: ""
  - title: 灵感来源
    links:
      - title: 优优网
        description: 网页灵感采集、网页模板、设计相关
        url: https://uiiiuiii.com/inspirations/ui
        logo: ""
      - title: pagecollective
        description: PC端页面收藏，找页面布局灵感
        url: https://pagecollective.com/
        logo: ""
      - title: screenlane
        description: 移动端页面收藏，找设计灵感
        url: https://screenlane.com/
        logo: ""
      - title: webdesignerdepot
        description: 设计网站&博客，界面可定制
        url: https://www.webdesignerdepot.com
        logo: ""
      - title: xmind 脑图合集
        description: 可以从一些优秀案例提取灵感，制作更清晰好看的脑图
        url: https://xmind.app/share/
        logo: ""
  - title: 在线设计
    links:
      - title: pixso
        description: 在线设计协作工具，丰富的设计资源
        url: https://pixso.cn/
        logo: ""
