title: 前端相关
icon: i-fa-html5
subMenu:
  - title: css 相关
    links:
      - title: css 动画工具
        description: "css3动画工具,css3动画效果,Css3动画参考"
        url: "https://www.w3cways.com/css3-animation-tool"
        logo: ""
      - title: animista - css animation
        description: 提供了一系列预设的动画
        url: "https://animista.net/play/basic"
        logo: ""
      - title: css-loaders
        description: 纯 css 加载动画，只用一个 div
        url: https://css-loaders.com/
        logo: ""
      - title: toptal css sprite
        description: 生成css雪碧图
        url: https://www.toptal.com/developers/css/sprite-generator
        logo: ""
      - title: cssportal
        description: css 相关工具，svg文字动画等
        url: https://www.cssportal.com/css-animated-text-generator/
        logo: ""
  - title: 性能相关
    links:
      - title: Pingdom
        description: 免费的网站速度测试，可以分析网站的加载速度及优化说明
        url: "https://tools.pingdom.com/"
        logo: pingdom.png
  - title: 工具库
    links:
      - title: bpmn 流程建模工具
        description: 生成业务流程模型的工具，类似流程图
        url: "https://bpmn.io/toolkit/bpmn-js/"
        logo: ""
      - title: MDX
        description: markdown 中通过 jsx 渲染组件，组件中插入 markdown
        url: "https://mdxjs.com/docs/"
        logo: mdx.png
      - title: rrweb 录制网页
        description: Web 录制与回放的工具库
        url: https://www.rrweb.io/
        logo: ""
      - title: 汉字拼音转换
        description: 汉字拼音转换库
        url: https://github.com/zh-lx/pinyin-pro
        logo: ""
  - title: 组件库
    links:
      - title: handsome-css
        description: 有趣开源的纯css特效组件
        url: https://www.handsome-css.com/
        logo: ""
  - title: 动画库
    links:
      - title: GreenSock
        description: 一个行业标准JavaScript动画库，可以制作出在每个主要浏览器中都能工作的高性能动画。
        url: "https://greensock.com/"
        logo: greensock.png
      - title: framer - motion 动画控制库
        description: Framer Motion is a production-ready React animation and gesture library.
        url: https://www.framer.com/motion/
        logo: ""
      - title: vue motion 动画库
        description: 结合 vueuse 使用的动画库
        url: https://motion.vueuse.org/
        logo: ""
      - title: spritejs
        description: 跨平台的高性能图形系统
        url: http://spritejs.com
        logo: ""
      - title: matter.js
        description: 2D 刚体物理引擎
        url: https://brm.io/matter-js/
        logo: ""
  - title: 解决方案
    links:
      - title: 帆软BI（finebi）
        description: 大数据分析的BI软件平台
        url: "https://www.finebi.com/"
        logo: finebi.png
      - title: umami
        description: 开源的 Google Analytics 替代方案，可以私有部署
        url: https://umami.is/
        logo: ""
