title: 学习资源
icon: i-fa-book
subMenu:
  - title: RSS 相关
    links:
      - title: RSSHub
        description: 开源、简单易用、易于扩展的 RSS 生成器
        url: "https://docs.rsshub.app/"
        logo: rsshub.png
      - title: feedly
        description: rss 订阅源在线阅读，主动关心感兴趣的信息流
        url: "https://feedly.com"
        logo: feedly.png
  - title: 知识输入
    links:
      - title: roadmap - 开发学习路线
        description: 开发人员推荐学习路线，各个领域知识面概括
        url: https://roadmap.sh/
        logo: ""
      - title: patterns learning
        description: 在线学习设计模式（react、vue， etc..），也可以下载PDF阅读
        url: https://www.patterns.dev/
        logo: ""
      - title: google developer - web
        description: Build the next generation of web experiences.
        url: "https://developers.google.cn/web"
        logo: google-developer-web.png
  - title: 独立开发
    links:
      - title: w2solo
        description: 独立开发者社区
        url: https://w2solo.com/
        logo: ""
